import type { AppState } from '../shared/schema'

export const getPanelText = (language: AppState['settings']['language']) =>
  language === 'en'
    ? {
        switchEyebrow: 'Provider profiles',
        switchTitle: 'Routing',
        switchDescription:
          'Save Claude and Codex API profiles here. The desktop app will inject the active profile into each CLI run.',
        switchStorageNote: 'Profiles are stored locally in this app workspace.',
        profileName: 'Profile name',
        apiKey: 'API key',
        baseUrl: 'Base URL',
        baseUrlNote: 'Leave Base URL blank to use the official endpoint.',
        addProfile: 'Add profile',
        activateProfile: 'Use profile',
        activeProfile: 'Active',
        removeProfile: 'Remove',
        noProfiles: 'No profiles yet.',
        noProfilesDescription: 'Add a profile to switch this provider to another API endpoint.',
        importTitle: 'Import from cc-switch',
        importDescription:
          'Bring Claude and Codex routing profiles over from a cc-switch database or SQL export.',
        importDefault: 'Import default db',
        importChooseFile: 'Choose .db or .sql',
        importPending: 'Importing cc-switch profiles...',
        importSupportedFiles:
          'Supports ~/.cc-switch/cc-switch.db and cc-switch SQL export files.',
        importSummary: (
          source: string,
          total: number,
          claudeCount: number,
          codexCount: number,
          addedCount: number,
          updatedCount: number,
        ) =>
          `Imported ${total} profiles from ${source} (Claude ${claudeCount}, Codex ${codexCount}). Added ${addedCount}, updated ${updatedCount}.`,
        importError: 'Unable to import cc-switch routing settings.',
        importTooLarge:
          'That cc-switch export is too large to upload. Use "Import default db" or choose a smaller SQL export.',
        setupTitle: 'One-click environment setup',
        setupDescription:
          'Check your local environment and install only the missing tools for this desktop app.',
        setupMissingListTitle: 'Missing tools',
        setupMissingListDescription: 'Only the items below still need installation.',
        installMissingTools: 'Install missing tools',
        cliUpdateTitle: 'Update CLI version',
        cliUpdateDescription:
          'Update Claude CLI, Codex CLI, or both. Leave the version blank to install the latest release.',
        cliUpdateTarget: 'CLI',
        cliUpdateTargetAll: 'Claude + Codex',
        cliUpdateVersion: 'Version',
        cliUpdateVersionPlaceholder: 'latest',
        cliUpdateVersionNote: 'Supports npm versions or dist-tags, such as latest, 1.2.3, or beta.',
        cliUpdateButton: 'Update CLI',
        resilientProxyTitle: 'Auto-retry proxy',
        resilientProxyDescription:
          'Automatically retry interrupted AI streams. Only affects runs from this app.',
        resilientProxyFootnote:
          'Local to this app only; it does not change your global CLI settings.',
        resilientProxyEnabled: 'Enabled',
        resilientProxyDisabled: 'Disabled',
        cliRoutingEnabled: 'CLI routing',
        cliRoutingDescription: 'When enabled, use the API keys below instead of CLI defaults.',
        routingTabProviders: 'Providers',
        routingTabProxy: 'Auto-retry',
        proxyStatus: 'Status',
        proxyStallTimeout: 'Stall timeout',
        proxyStallTimeoutNote: 'Max silence between stream chunks before retrying.',
        proxyFirstByteTimeout: 'First-byte timeout',
        proxyFirstByteTimeoutNote: 'Max wait for the first response byte.',
        proxyMaxRetries: 'Max retries',
        proxyMaxRetriesNote: '-1 = unlimited.',
        proxyUnlimited: 'Unlimited',
        proxyFeatureTitle: 'How it works',
        proxyFeatures: [
          'Detects disconnections, stalls, and timeouts in streaming responses.',
          'Buffers partial text and retries from where it left off.',
          'Exponential backoff with jitter to avoid thundering herd.',
          'Heartbeat frames keep connections alive.',
        ] as string[],
        proxyStatsTitle: 'Stats',
        proxyStatsRequests: 'Requests',
        proxyStatsDisconnects: 'Disconnects',
        proxyStatsRecoveries: 'Recovered',
        proxyStatsFailures: 'Failed',
        proxyStatsCurrentSession: 'This launch',
        proxyStatsTimeFilter: 'Time range',
        proxyStatsAll: 'All',
        proxyStatsLast1h: '1h',
        proxyStatsLast24h: '24h',
        proxyStatsReset: 'Reset',
        runSetup: 'Run one-click setup',
        rerunSetup: 'Run again',
        refreshSetup: 'Refresh',
        setupLogs: 'Setup logs',
        setupIdle: 'Not started yet.',
        setupLoading: 'Loading setup status...',
        setupDetectedMissing: 'Missing tools detected.',
        setupReadyToInstall: 'One click will install only the missing tools below.',
        setupRunning: 'Setup is running...',
        setupSuccess: 'Setup completed.',
        setupError: 'Setup failed.',
        setupUnsupported: 'This feature is currently available on Windows only.',
        switchReminder: (providerLabel: string) =>
          `${providerLabel} needs API configuration. Add or activate a profile in the routing tab.`,
        setupReminder: (providerLabel: string) =>
          `${providerLabel} CLI is unavailable. Open the settings tab and run one-click environment setup.`,
      }
    : {
        switchEyebrow: '接口配置',
        switchTitle: '路由',
        switchDescription:
          '保存 Claude 和 Codex 的 API 配置。每次 CLI 运行时，桌面应用会自动注入当前启用的配置。',
        switchStorageNote: '仅在本应用内生效。',
        profileName: '名称',
        apiKey: 'API Key',
        baseUrl: 'Base URL',
        baseUrlNote: '留空 Base URL 即使用官方接口地址。',
        addProfile: '添加',
        activateProfile: '启用',
        activeProfile: '当前启用',
        removeProfile: '移除',
        noProfiles: '暂无配置。',
        noProfilesDescription: '添加一个配置即可将此服务商切换到其他 API 地址。',
        importTitle: '从 cc-switch 导入',
        importDescription:
          '从 cc-switch 数据库或 SQL 导出文件中导入 Claude 和 Codex 的配置。',
        importDefault: '导入默认数据库',
        importChooseFile: '选择 .db 或 .sql 文件',
        importPending: '正在导入配置...',
        importSupportedFiles:
          '支持 ~/.cc-switch/cc-switch.db 和 cc-switch SQL 导出文件。',
        importSummary: (
          source: string,
          total: number,
          claudeCount: number,
          codexCount: number,
          addedCount: number,
          updatedCount: number,
        ) =>
          `已从 ${source} 导入 ${total} 个配置（Claude ${claudeCount}，Codex ${codexCount}）。新增 ${addedCount} 个，更新 ${updatedCount} 个。`,
        importError: '无法导入 cc-switch 配置。',
        importTooLarge:
          '所选 cc-switch 导出文件太大，无法上传。请使用“导入默认数据库”或选择更小的 SQL 导出文件。',
        setupTitle: '一键环境安装',
        setupDescription:
          '检查本机环境，只为这个桌面应用安装缺失项。',
        setupMissingListTitle: '缺失项',
        setupMissingListDescription: '仅下列项目仍需要安装。',
        installMissingTools: '一键安装缺失环境',
        cliUpdateTitle: '更新 CLI 版本',
        cliUpdateDescription:
          '更新 Claude CLI、Codex CLI，或同时更新两者。版本留空时默认安装最新版。',
        cliUpdateTarget: 'CLI',
        cliUpdateTargetAll: 'Claude + Codex',
        cliUpdateVersion: '版本',
        cliUpdateVersionPlaceholder: 'latest',
        cliUpdateVersionNote: '支持 npm 版本号或标签，例如 latest、1.2.3、beta。',
        cliUpdateButton: '更新 CLI',
        resilientProxyTitle: '断线续传',
        resilientProxyDescription:
          '流式响应中断时自动重试，从断点处继续。仅影响本应用发起的请求。',
        resilientProxyFootnote:
          '仅在本应用内生效。',
        resilientProxyEnabled: '已启用',
        resilientProxyDisabled: '已关闭',
        cliRoutingEnabled: '启用',
        cliRoutingDescription: '启用后使用下方配置替代 CLI 默认值。',
        routingTabProviders: '接口配置',
        routingTabProxy: '断线续传',
        proxyStatus: '启用',
        proxyStallTimeout: '停顿超时',
        proxyStallTimeoutNote: '两个数据块之间的最大等待时间。',
        proxyFirstByteTimeout: '首字节超时',
        proxyFirstByteTimeoutNote: '等待首个响应字节的最长时间。',
        proxyMaxRetries: '最大重试',
        proxyMaxRetriesNote: '-1 表示无限重试。',
        proxyUnlimited: '无限',
        proxyFeatureTitle: '工作原理',
        proxyFeatures: [
          '检测流中的断连、停顿和超时。',
          '缓存已收到的文本，从中断处继续。',
          '指数退避加随机抖动，避免重试风暴。',
          '心跳帧保持连接存活。',
        ] as string[],
        proxyStatsTitle: '统计',
        proxyStatsRequests: '请求',
        proxyStatsDisconnects: '断连',
        proxyStatsRecoveries: '已恢复',
        proxyStatsFailures: '失败',
        proxyStatsCurrentSession: '本次启动',
        proxyStatsTimeFilter: '时间范围',
        proxyStatsAll: '全部',
        proxyStatsLast1h: '1h',
        proxyStatsLast24h: '24h',
        proxyStatsReset: '重置',
        runSetup: '运行一键安装',
        rerunSetup: '重新运行',
        refreshSetup: '刷新',
        setupLogs: '安装日志',
        setupIdle: '尚未开始。',
        setupLoading: '正在加载安装状态...',
        setupDetectedMissing: '检测到缺失环境。',
        setupReadyToInstall: '仅会安装下方缺失项。',
        setupRunning: '正在安装...',
        setupSuccess: '安装完成。',
        setupError: '安装失败。',
        setupUnsupported: '该功能目前仅支持 Windows。',
        switchReminder: (providerLabel: string) =>
          `${providerLabel} 需要 API 配置，请在接口配置页添加或启用。`,
        setupReminder: (providerLabel: string) =>
          `${providerLabel} CLI 当前不可用，请打开设置页运行一键环境安装。`,
      }

export type PanelText = ReturnType<typeof getPanelText>

export const getTopTabText = (language: AppState['settings']['language']) =>
  language === 'en'
    ? {
        navLabel: 'App sections',
        ambience: 'Chill Vibe',
        routing: 'Routing',
        settings: 'Settings',
      }
    : {
        navLabel: '应用分区',
        ambience: 'Chill Vibe',
        routing: '接口',
        settings: '设置',
      }

export const getResilientProxyText = (panelText: PanelText) => ({
  title: panelText.resilientProxyTitle,
  description: panelText.resilientProxyDescription,
  footnote: panelText.resilientProxyFootnote,
  enabled: panelText.resilientProxyEnabled,
  disabled: panelText.resilientProxyDisabled,
  cliRoutingEnabled: panelText.cliRoutingEnabled,
  cliRoutingDescription: panelText.cliRoutingDescription,
  tabProviders: panelText.routingTabProviders,
  tabProxy: panelText.routingTabProxy,
  status: panelText.proxyStatus,
  stallTimeout: panelText.proxyStallTimeout,
  stallTimeoutNote: panelText.proxyStallTimeoutNote,
  firstByteTimeout: panelText.proxyFirstByteTimeout,
  firstByteTimeoutNote: panelText.proxyFirstByteTimeoutNote,
  maxRetries: panelText.proxyMaxRetries,
  maxRetriesNote: panelText.proxyMaxRetriesNote,
  unlimited: panelText.proxyUnlimited,
  featureTitle: panelText.proxyFeatureTitle,
  features: panelText.proxyFeatures,
  statsTitle: panelText.proxyStatsTitle,
  statsRequests: panelText.proxyStatsRequests,
  statsDisconnects: panelText.proxyStatsDisconnects,
  statsRecoveries: panelText.proxyStatsRecoveries,
  statsFailures: panelText.proxyStatsFailures,
  statsCurrentSession: panelText.proxyStatsCurrentSession,
  statsTimeFilter: panelText.proxyStatsTimeFilter,
  statsAll: panelText.proxyStatsAll,
  statsLast1h: panelText.proxyStatsLast1h,
  statsLast24h: panelText.proxyStatsLast24h,
  statsReset: panelText.proxyStatsReset,
})

export const getOnboardingText = (language: AppState['settings']['language']) =>
  language === 'en'
    ? {
        eyebrow: 'First launch',
        title: 'Quick start',
        loadingTitle: 'Preparing your setup guide',
        loadingDescription: 'Checking your local environment and whether cc-switch settings are available.',
        setupStepTitle: 'Environment setup',
        importStepTitle: 'Import from cc-switch',
        environmentReady: 'Environment ready.',
        setupSkipped: 'Skipped for now.',
        setupUnsupported: 'Automatic setup is not available in this environment.',
        missingTools: (names: string) => `Still missing: ${names}.`,
        ccSwitchMissing: 'No cc-switch settings found.',
        ccSwitchDetected: (source: string) => `Found settings at ${source}.`,
        importSkipped: 'Skipped for now.',
        importPrompt: (source: string) => `Import Claude and Codex profiles from ${source}?`,
        importNow: 'Import now',
        skipForNow: 'Skip for now',
        openWorkspace: 'Open workspace',
        completeTitle: 'You are ready to go',
        completeDescription:
          'The quick start guide has finished. You can still rerun setup or import cc-switch profiles later from Settings and Routing.',
        runningSetup: 'Installing the recommended tools automatically.',
        retrySetup: 'Run setup again',
        installing: 'Installing...',
        languageToggle: 'Guide language',
      }
    : {
        eyebrow: '首次启动',
        title: '快速上手',
        loadingTitle: '正在准备启动向导',
        loadingDescription: '正在检查本地环境，以及是否存在 cc-switch 配置。',
        setupStepTitle: '环境安装',
        importStepTitle: 'cc-switch 导入',
        environmentReady: '环境已就绪。',
        setupSkipped: '这一步已暂时跳过。',
        setupUnsupported: '当前环境不支持自动安装。',
        missingTools: (names: string) => `仍缺少：${names}。`,
        ccSwitchMissing: '未发现 cc-switch 配置。',
        ccSwitchDetected: (source: string) => `已检测到 ${source}。`,
        importSkipped: '这一步已暂时跳过。',
        importPrompt: (source: string) => `要从 ${source} 导入 Claude 和 Codex 配置吗？`,
        importNow: '立即导入',
        skipForNow: '暂时跳过',
        openWorkspace: '进入工作台',
        completeTitle: '已经可以开始使用了',
        completeDescription:
          '快速向导已完成，后续仍可以在设置和接口页重新执行环境安装或导入 cc-switch。',
        runningSetup: '正在自动安装推荐环境。',
        retrySetup: '重新执行环境安装',
        installing: '安装中...',
        languageToggle: '向导语言',
      }
