import type { AppLanguage } from '../../../shared/schema'
import type { SettingsCategoryId } from './settings-model'

const zh = {
  navLabel: '设置分类',
  searchLabel: '搜索设置',
  searchPlaceholder: '搜索设置，例如「代理」「模型」',
  searchEmpty: '没有找到匹配的设置项。换个词试试，比如「proxy」或「主题」。',
  searchResultsTitle: (count: number) => `找到 ${count} 项`,
  advancedSummary: '高级设置',
  advancedNote: '平时不需要动。展开可以看到这一类的全部选项。',
  leaveAlone: '一般不用动',
  leaveAloneNote: '下面是实验功能和危险操作，不清楚用途时请保持原样。',
  experimentalTag: '实验',
  dangerTag: '危险',
  basicsLabel: '基础',
  basicsNote: '新手只需要看这四项。其他都在左边的分类里。',
  categories: {
    'get-started': '开始使用',
    models: '模型与对话',
    appearance: '外观与编辑',
    automation: '自动化与工具',
    network: '网络与安全',
    system: '系统',
  } satisfies Record<SettingsCategoryId, string>,
  categoryNotes: {
    'get-started': '装好 CLI、连上账号，就能开始用了。',
    models: '新会话默认用什么模型、怎么思考。',
    appearance: '语言、主题、字体和编辑器。',
    automation: '让会话自己醒来、自己催、反复跑。',
    network: '断线重连和 Agent 权限边界。',
    system: '更新、通用行为，以及最下面的实验功能和数据清理。',
  } satisfies Record<SettingsCategoryId, string>,
  accountSummary: {
    routingOff: '接口路由已关闭：Claude / Codex 用各自 CLI 自己登录的账号。',
    using: (provider: string, profile: string) => `${provider}：正在用「${profile}」`,
    noProfile: (provider: string) => `${provider}：还没有启用的配置`,
    open: '去「接口」选项卡管理',
  },
  health: {
    title: '环境健康',
    refresh: '重新检测',
    allOk: '环境正常：CLI、账号、版本都没问题',
    cli: 'CLI 已安装',
    account: '账号可用',
    version: '版本兼容',
    state: {
      ok: '正常',
      warn: '需要处理',
      error: '有问题',
      unknown: '检测中',
    },
    detail: {
      cliOk: 'Claude CLI 和 Codex CLI 都能用。',
      cliPartial: (names: string) => `目前只有 ${names} 可用。`,
      cliMissing: '还没有装 Claude CLI 或 Codex CLI。',
      accountOk: '已经有可用的账号或 API key。',
      accountCliLogin: '接口路由已关闭，使用 CLI 自己登录的账号。',
      accountMissing: '还没有填 API key。',
      versionOk: '正在使用验证过的 CLI 版本。',
      versionMismatch: (provider: string) => `${provider} 的版本和本 IDE 验证过的不一致。`,
      unknown: '正在检测……',
    },
    fix: {
      'install-cli': '一键安装',
      'connect-account': '去连接账号',
      'install-compat': '下载兼容版',
      'activate-compat': '切换到兼容版',
    },
  },
  wizard: {
    stepInstall: '装 CLI',
    stepAccount: '连账号',
    stepModel: '选模型',
    accountTitle: '连接账号',
    accountDescription: '填一个 API key，或者从 cc-switch 导入现成配置。也可以先跳过，之后在设置里再填。',
    accountProvider: '给谁用',
    accountApiKey: 'API key',
    accountBaseUrl: '中转地址（可留空）',
    accountSave: '保存并继续',
    accountSaved: '账号已保存。',
    accountSkipped: '这一步已暂时跳过。',
    accountConnected: (provider: string) => `已为 ${provider} 保存 API key。`,
    accountExisting: '已经有可用的账号配置。',
    accountPending: '还没有连接账号。',
    modelTitle: '选择默认模型',
    modelDescription: '新会话默认用这个模型。之后随时可以在设置或每张卡上改。',
    modelConfirm: '就用这个',
    modelPending: '还没有选默认模型。',
    modelConfirmed: (claude: string, codex: string) => `Claude 用 ${claude}，Codex 用 ${codex}。`,
  },
}

const en: typeof zh = {
  navLabel: 'Settings categories',
  searchLabel: 'Search settings',
  searchPlaceholder: 'Search settings, e.g. "proxy" or "model"',
  searchEmpty: 'No settings match. Try another word, like "proxy" or "theme".',
  searchResultsTitle: (count: number) => `${count} result${count === 1 ? '' : 's'}`,
  advancedSummary: 'Advanced settings',
  advancedNote: 'Rarely needed. Expand to see everything in this category.',
  leaveAlone: 'Usually leave as is',
  leaveAloneNote: 'Experimental features and dangerous actions live below. Leave them alone unless you know what they do.',
  experimentalTag: 'Experimental',
  dangerTag: 'Danger',
  basicsLabel: 'Basics',
  basicsNote: 'These four are all a beginner needs. Everything else lives in the categories on the left.',
  categories: {
    'get-started': 'Get started',
    models: 'Models & chat',
    appearance: 'Appearance & editor',
    automation: 'Automation & tools',
    network: 'Network & safety',
    system: 'System',
  },
  categoryNotes: {
    'get-started': 'Install the CLI, connect an account, and you are ready.',
    models: 'Which model new chats use and how it reasons.',
    appearance: 'Language, theme, fonts and the editor.',
    automation: 'Let chats wake up, nudge themselves and repeat.',
    network: 'Reconnection and the agent permission boundary.',
    system: 'Updates, general behavior, then experimental features and data cleanup at the bottom.',
  },
  accountSummary: {
    routingOff: 'Routing is off: Claude / Codex use their own CLI login.',
    using: (provider: string, profile: string) => `${provider}: using "${profile}"`,
    noProfile: (provider: string) => `${provider}: no active profile yet`,
    open: 'Manage in the Routing tab',
  },
  health: {
    title: 'Environment health',
    refresh: 'Re-check',
    allOk: 'All good: CLI, account and version are fine',
    cli: 'CLI installed',
    account: 'Account usable',
    version: 'Version compatible',
    state: {
      ok: 'OK',
      warn: 'Needs attention',
      error: 'Problem',
      unknown: 'Checking',
    },
    detail: {
      cliOk: 'Both Claude CLI and Codex CLI are available.',
      cliPartial: (names: string) => `Only ${names} is available right now.`,
      cliMissing: 'Neither Claude CLI nor Codex CLI is installed.',
      accountOk: 'A usable account or API key is configured.',
      accountCliLogin: 'Routing is off, so the CLI uses its own login.',
      accountMissing: 'No API key yet.',
      versionOk: 'Using the verified CLI versions.',
      versionMismatch: (provider: string) => `${provider} is not on the version this IDE was verified with.`,
      unknown: 'Checking…',
    },
    fix: {
      'install-cli': 'Install',
      'connect-account': 'Connect account',
      'install-compat': 'Download compatible build',
      'activate-compat': 'Switch to compatible build',
    },
  },
  wizard: {
    stepInstall: 'Install CLI',
    stepAccount: 'Connect account',
    stepModel: 'Pick a model',
    accountTitle: 'Connect an account',
    accountDescription: 'Paste an API key, or import an existing cc-switch setup. You can skip this and fill it in later in Settings.',
    accountProvider: 'For',
    accountApiKey: 'API key',
    accountBaseUrl: 'Relay base URL (optional)',
    accountSave: 'Save and continue',
    accountSaved: 'Account saved.',
    accountSkipped: 'Skipped for now.',
    accountConnected: (provider: string) => `Saved an API key for ${provider}.`,
    accountExisting: 'A usable account is already configured.',
    accountPending: 'No account connected yet.',
    modelTitle: 'Pick a default model',
    modelDescription: 'New chats start with this model. You can change it any time in Settings or on each card.',
    modelConfirm: 'Use this',
    modelPending: 'No default model chosen yet.',
    modelConfirmed: (claude: string, codex: string) => `Claude uses ${claude}, Codex uses ${codex}.`,
  },
}

export type SettingsPanelText = typeof zh

export const getSettingsPanelText = (language: AppLanguage): SettingsPanelText =>
  language === 'en' ? en : zh
